### ISSUE TITLE
flask server 404 error

### ISSUE THREAD

**Issue by Minchan-Kim** [Soyeon-ErinLee/Dobby-AI#7]
result page를 띄울 때마다
"GET /static/js/query1.js HTTP/1.1" 404 -
이 에러가 계속 발생합니다.
url_for를 써야 되는 것 아닌가 싶습니다.

**Comment by Soyeon-ErinLee** [comment]
~url/result 페이지가 아예 안뜨나요? 확인해보겠습니다

**Comment by Minchan-Kim** [comment]
result 페이지는 뜨고, 업로드한 파일 재생 되는 것도 확인했습니다. 다만 Flask가 query1.js를 못찾아서 저런 에러가 나는 것 같습니다.

**Comment by Soyeon-ErinLee** [comment]
result.html을 업데이트 하였습니다. 해당 파일로 다시 시도해주세요.
